### ISSUE TITLE
Idea: Add `batch_with_argument_passing` to pallet-utility

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot-sdk#6371]
(Naming is shitty) The idea is that similar to `batch` you can batch multiple calls together, but you are able to use outputs from the previous transaction as input for the next transaction. An output of a transaction is an event. So, if you have an event like this:

```
	Self::deposit_event(Event::<T, I>::Submitted { index, track, proposal });
```

You would be able to use `index`, `track` or `proposal` as identifier for the values to pass them into the next transaction. The identifiers and the values could be stored in the [`dispatch_context`](https://docs.rs/frame-support/latest/frame_support/dispatch_context/index.html). It require changing the macros a little bit to generate some code that makes it easy to put the event into dispatch context. Otherwise it should be straightforward to implement.

**Comment by MrishoLukamba** [comment]
it should be "chain batching".

Here is the effect for it
1. The calls are not atomic

I will take it @bkchr assign it.

**Comment by MrishoLukamba** [comment]
on it

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/can-pallet-revive-help-improve-polkadots-ux/12923/23

**Comment by jak-pan** [comment]
We had similar idea here https://github.com/galacticcouncil/hydration-node/issues/1005 
This however will come with even more problems for tracking transactions (especially from other block phases) I would encourage to look at this also. We have implemented very hacky way to track chain of transactions, but it could be implemented better to track batched (chained) execution context that might be in scope for this here. 
https://github.com/galacticcouncil/hydration-node/pull/910/files#diff-026eb44a10a5ecac9e6e19c5a24b9b1702d5aab995692fcec7495da01556de0c (pallet broadcast is the important part but I would expect this to not be hacked up in such way)

**Comment by bkchr** [comment]
> This however will come with even more problems for tracking transactions (especially from other block phases) I would encourage to look at this also

Why would it change anything for tracking transactions?

**Comment by jak-pan** [comment]
Maybe it wouldn't necessarily make it much worse, but it's bad as is. 
 If it's used which I bet it will, it will be untrackable. Or at least bad enough that it will be huge mess.

**Comment by bkchr** [comment]
@jak-pan maybe this tracking stuff should be part of a different issue. I still don't fully get what you are tracking there. Having some writeup of what you want to achieve, could probably help to help you there :)

**Comment by Doordashcon** [comment]
@MrishoLukamba still working on this?

**Comment by ggwpez** [comment]
I am not convinced that we should add such complicated features to FRAME anymore.

The same can be achieved with XCM or a Smart contract that gets deployed and un-deployed in the same TX.  
Both of those primitives are much more powerful and dont burden us with maintenance a some niche feature that we maybe use once.

Further, the proposed implementation #10234 would force each pallet to first adopt this new pattern, which kind of undoes lots of its proposed advantage.

**Comment by jessechejieh** [comment]
I mostly agree with @ggwpez 

The SDK is already feature rich and just needs better communicating about what's currently possible.

But also some users might not want to use smart contracts

**Comment by xlc** [comment]
This can be a useful feature BUT it is complicated and enables many new possibilities, which is both good and bad thing. Not everyone needs such possibilities and surely it adds lot more attack surfaces. The code by its own might be perfectly good but who knows what could happen when combined with some parachain specific code?
At very minimal, it should not be part of the core frame system / pallet utility so it is strictly opt-in feature for ecosystem teams.
And I think the general direction should be improving smart contracts or XCM compossibility, instead of making extrinsic interface programmable.

**Comment by jessechejieh** [comment]
Consensus so far is this shouldn't live in core frame-support/pallet-utility, and the contract/XCM layer is the preferred direction for call composition.

**Comment by bkchr** [comment]
> The same can be achieved with XCM or a Smart contract that gets deployed and un-deployed in the same TX.

How? XCM can not do anything that is similar to what I'm proposing? Also deploying and un deploying a smart contract sounds quite heavy? Plus smart contracts can not read this data either.

> Further, the proposed implementation [#10234](https://github.com/paritytech/polkadot-sdk/pull/10234) would force each pallet to first adopt this new pattern, which kind of undoes lots of its proposed advantage.

Looking at this pull request, I don't see a need for this new pattern. It should not be required, because the fields already have names.



> At very minimal, it should not be part of the core frame system / pallet utility so it is strictly opt-in feature for ecosystem teams.

We could disable it by default.

**Comment by xlc** [comment]
pallet-xcm have `execute` extrinsic to execute XCM message locally so it can be used to do work locally. XCM right now don't have a solution for this specific problem, but we can improve XCM instead of updating pallet.

With the smart contract side, there are many ways to go. One will be just have purposed built contracts and deploy it. The contract can selfdestruct if needed. The user send 1 tx so there is no UX side differences. Another way is to have a predeployed contract factory / batch executor. Then we just encode whatever data needed and invoke the utility contract to do the work.

**Comment by bkchr** [comment]
> pallet-xcm have `execute` extrinsic to execute XCM message locally so it can be used to do work locally. XCM right now don't have a solution for this specific problem, but we can improve XCM instead of updating pallet.

Yeah for sure, but already right now XCM is not as generic as this. It will always kind of lack behind, because it represents a stable interface and not something more "fluid" as pallets.

> With the smart contract side, there are many ways to go. One will be just have purposed built contracts and deploy it. The contract can selfdestruct if needed. The user send 1 tx so there is no UX side differences. Another way is to have a predeployed contract factory / batch executor. Then we just encode whatever data needed and invoke the utility contract to do the work.

Someone could also think about using something similar like XCM query  and building PVM programs on the fly that are doing the actual work on chain. So kind of similar to smart contracts, but with more access to the chain.

**Comment by jessechejieh** [comment]
> Someone could also think about ... building PVM programs on the fly that are doing the actual work on chain. So kind of similar to smart contracts, but with more access to the chain.

This is close to what #12457 is adding?

The `UncheckedRuntime` precompile lets a PVM program do call dispatch + raw storage reads, so the output→input passing could sit on top of that instead of in FRAME.
