### ISSUE TITLE
Polkadot node stuck in `Emergency` phase

### ISSUE THREAD

**Issue by sigurpol** [paritytech/polkadot-sdk#8302]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

After https://github.com/paritytech/polkadot-sdk/pull/8127 got merged, we noticed that when  running `polkadot` binary like below:

```bash
./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all
```

Logs from the polkadot node:

```bash
➜ polkadot-sdk (79b28b3185d0) ✗ ./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all
CLI parameter `--execution` has no effect anymore and will be removed in the future!
2025-04-23 10:18:52.457  INFO main sc_cli::runner: Parity Polkadot
2025-04-23 10:18:52.457  INFO main sc_cli::runner: ✌️  version 1.18.0-79b28b3185d
2025-04-23 10:18:52.457  INFO main sc_cli::runner: ❤️   by Parity Technologies <admin@parity.io>, 2017-2025
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 📋 Chain specification: Development
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 🏷  Node name: Alice
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 👤 Role: AUTHORITY
2025-04-23 10:18:52.457  INFO main sc_cli::runner: 💾 Database: RocksDb at /tmp/substrateZKIjnf/chains/westend_dev/db/full
2025-04-23 10:19:13.668 DEBUG main runtime::staking: [0] 💸 Starting the first era.
2025-04-23 10:19:13.668 DEBUG main runtime::election-provider: [#0] 🗳  closed signed phase, found solution? false, discarded 0
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  No solution queued, falling back to instant fallback.
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  Failed to finalize election round. reason ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 ERROR main runtime::election-provider: [#0] 🗳  Entering emergency mode: ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  Starting phase Emergency, round 1.
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  ElectionProvider::elect(0) => Err(ElectionError::Feasibility(SnapshotUnavailable))
2025-04-23 10:19:13.668  WARN main runtime::staking: [0] 💸 election provider failed due to ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 DEBUG main runtime: No initial validator provided by `SessionManager`, use session config keys to generate initial validator set.
2025-04-23 10:19:13.668 DEBUG main runtime::staking: [0] 💸 Starting the first era.
2025-04-23 10:19:13.668 DEBUG main runtime::election-provider: [#0] 🗳  closed signed phase, found solution? false, discarded 0
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  No solution queued, falling back to instant fallback.
2025-04-23 10:19:13.668  WARN main runtime::election-provider: [#0] 🗳  Failed to finalize election round. reason ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668 ERROR main runtime::election-provider: [#0] 🗳  Entering emergency mode: ElectionError::Feasibility(SnapshotUnavailable)
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  Starting phase Emergency, round 1.
2025-04-23 10:19:13.668  INFO main runtime::election-provider: [#0] 🗳  ElectionProvider::elect(0) => Err(ElectionError::Feasibility(SnapshotUnavailable))
2025-04-23 10:19:13.668  WARN main runtime::staking: [0] 💸 election provider failed due to ElectionError::Feasibility(SnapshotUnavailable)
```

the Phase shows up as `Emergency` and never gets into the `Signed` phase.

This cause the polkadot-staking-miner CI tests to systematically fail, see the issue [here](https://github.com/paritytech/polkadot-staking-miner/issues/1031).

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/b8a3e9c3-1086-4cfc-9693-952209fe36c5" />

### Steps to reproduce

1. build `polkadot` binary vs latest and greatest SDK master
2. run `./target/release/polkadot --chain westend-dev --tmp --alice --unsafe-force-node-key-generation --execution Native --offchain-worker=Always --rpc-cors=all`

Expected:
- Phase should transition to `Signed`, `Unsigned` etc

Actual:
- Phase stuck in `Emergency`

**Comment by sigurpol** [comment]
@kianenigma , @Ank4n  can you PTAL when you have time 🙏 ?

**Comment by sigurpol** [comment]
`is_genesis` is false so we end up calling `new_session` instead of `new_session_genesis`  so when starting the node, the session pallet should call `new_session_genesis` at genesis, but it's calling `new_session`.
The proposed fix in `do_elect` to check block number regardless of `is_genesis` value I think it might work but is indeed a bit more of a workaround to avoid maybe bigger changes in the session manager...

**Comment by sigurpol** [comment]
Fixed by #8310 , I've verified it also fixes https://github.com/paritytech/polkadot-staking-miner/issues/1031

**Comment by arunjot12** [comment]
Hi @sigurpol @kianenigma  . I'm using branch stable2506 in my chain and I'm facing this same issue. Could you please provide suggestions for me?

**Comment by sigurpol** [comment]
👋  @arunjot12 ! Thanks for reaching out. I might need some extra info to understand  what you  want to do exactly with your chain. 
And more specifically I would also like to know:
- what node and runtime you are using
- what pallets 
- what configurations those pallets have
- any logs would help
- when the problem happens exactly (e.g. you are bootstrapping a new chain and you are stuck in Emergency phase etc)

**Comment by arunjot12** [comment]
Thank you for the reply @sigurpol . Actually one feature of runtime benchmarks was missing from the runtime. That's why the the election got failed. Thank you @sigurpol

**Comment by arunjot12** [comment]
Hi @sigurpol. I'm still facing this issue. I'm just doing the setup of 1 node with 1 minute era and 1 minute epoch. When i stop the chain and start it with some time. It fails with
```

2025-08-29 15:09:10 [#673] 🗳  No solution queued, falling back to instant fallback.    
2025-08-29 15:09:10 [#673] 🗳  Failed to finalize election round. reason ElectionError::Feasibility(SnapshotUnavailable)    
2025-08-29 15:09:10 [#673] 🗳  Entering emergency mode: ElectionError::Feasibility(SnapshotUnavailable)    
2025-08-29 15:09:10 [#673] 🗳  Starting phase Emergency, round 28.    
2025-08-29 15:09:10 [#673] 🗳  ElectionProvider::elect(0) => Err(ElectionError::Feasibility(SnapshotUnavailable))    
2025-08-29 15:09:10 [673] 💸 election provider failed due to ElectionError::Feasibility(SnapshotUnavailable)    
```

**Comment by arunjot12** [comment]
I'm not able to skip the epoch. I'm using the branch of stable2506 of polkadot-sdk. Please help @sigurpol @kianenigma

**Comment by sigurpol** [comment]
👋  Not sure if we should continue here or in #9605 ...  That said, can you tell me the steps I would need to perform to reproduce your issue?  

What is your setup in terms of pallets and related configurations, especially around staking / EPMB pallet? 

Keep in mind that  the multi-block pallet needs time to create snapshot ( target snapshot : 1 block +  voter snapshot: `Pages` blocks, e.g. Westend Asset Hub = 32 Pages -> 32 blocks. How many pages in your setup?)

Plus you have Signed Phase - Unsigned Phase - Signed Validation Phase - Done - Export so 1min seems more than challenging as Era.

Your configuration has also an impact of the staking machinery via parameters like 

•  MaxElectingVoters: Total nominators considered
•  VoterSnapshotPerBlock: Voters per page
•  TargetSnapshotPerBlock: Validators per page
•  Staking parameters like MinValidatorBond, MinNominatorBond

Please provide your configuration!

As a note: validators come from accounts that registered as validators, and nominators come from accounts that registered as nominators, both stored in the staking pallet's on-chain storage and organized by the VoterList (bags-list) for efficient snapshot pagination. But I am afraid we might have ended up in a case where snapshot has never been created.

Beside knowing your configuration, can you try to increase era and epoch (e.g. era 15-30min / Epoch 3-5min or so) ?

Can you also provide full logs and not just this extract?

**Comment by arunjot12** [comment]
Hi @sigurpol . Thank you so much for your reply. 


This is my pallet-election-provider-multi-phase


```
parameter_types! {
    pub MaxNominations: u32 = <NposSolution16 as frame_election_provider_support::NposSolution>::LIMIT as u32;
    pub MaxElectingVoters: u32 = 40_000;
    pub MaxElectableTargets: u16 = 10_000;
    // OnChain values are lower.
    pub MaxOnChainElectingVoters: u32 = 5000;
    pub MaxOnChainElectableTargets: u16 = 1250;
    pub ElectionBoundsMultiPhase: ElectionBounds = ElectionBoundsBuilder::default()
        .voters_count(10_000.into()).targets_count(1_500.into()).build();
    pub ElectionBoundsOnChain: ElectionBounds = ElectionBoundsBuilder::default()
        .voters_count(5_000.into()).targets_count(1_250.into()).build();
    pub MaxElectingVotersSolution: u32 = 40_000;
    pub const SignedFixedDeposit: Balance = 1 * DOLLARS;
    pub const SignedDepositIncreaseFactor: Percent = Percent::from_percent(10);
    // The maximum winners that can be elected by the Election pallet which is equivalent to the
    // maximum active validators the staking pallet can have.
    pub MaxActiveValidators: u32 = 1000;
}

impl pallet_election_provider_multi_phase::MinerConfig for Runtime {
    type AccountId = AccountId;
    type MaxLength = MinerMaxLength;
    type MaxWeight = MinerMaxWeight;
    type Solution = NposSolution16;
    type MaxVotesPerVoter =
	<<Self as pallet_election_provider_multi_phase::Config>::DataProvider as ElectionDataProvider>::MaxVotesPerVoter;
    type MaxWinners = MaxActiveValidators;
    type MaxBackersPerWinner = MaxElectingVotersSolution;

    // The unsigned submissions have to respect the weight of the submit_unsigned call, thus their
    // weight estimate function is wired to this call's weight.
    fn solution_weight(v: u32, t: u32, a: u32, d: u32) -> Weight {
        <
			<Self as pallet_election_provider_multi_phase::Config>::WeightInfo
			as
			pallet_election_provider_multi_phase::WeightInfo
		>::submit_unsigned(v, t, a, d)
    }
}
```

This is same as substrate node. Even OnChainSeq is same as substrate


```
pub struct OnChainSeqPhragmen;
impl onchain::Config for OnChainSeqPhragmen {
    type System = Runtime;
    type Solver = SequentialPhragmen<
        AccountId,
        pallet_election_provider_multi_phase::SolutionAccuracyOf<Runtime>,
    >;
    type DataProvider = Staking;
    type WeightInfo = frame_election_provider_support::weights::SubstrateWeight<Runtime>;
    type Bounds = ElectionBoundsOnChain;
    type Sort = ConstBool<true>;
    type MaxBackersPerWinner = MaxElectingVotersSolution;
    type MaxWinnersPerPage = MaxActiveValidators;
}
```


This is my staking pallet config


```
parameter_types! {
    pub const SessionsPerEra: sp_staking::SessionIndex = 24; // 24 hours
    pub const BondingDuration: sp_staking::EraIndex = 28; // 28 days
    pub const SlashDeferDuration: sp_staking::EraIndex = 27; // 27 days
    pub const RewardCurve: &'static PiecewiseLinear<'static> = &REWARD_CURVE;
    pub const MaxNominatorRewardedPerValidator: u32 = 64;
    pub const MaxAuthorities: u32 = 100;
    pub OffchainRepeat: BlockNumber = 5;
    pub HistoryDepth: u32 = 84;
    pub const OffendingValidatorsThreshold: Perbill = Perbill::from_percent(17);
    pub const MaxControllersInDeprecationBatch: u32 = 5900;
}

pub struct StakingBenchmarkingConfig;
impl pallet_staking::BenchmarkingConfig for StakingBenchmarkingConfig {
    type MaxNominators = ConstU32<1000>;
    type MaxValidators = ConstU32<1000>;
}

/// Upper limit on the number of NPOS nominations.
const MAX_QUOTA_NOMINATIONS: u32 = 16;

impl pallet_staking::Config for Runtime {
    type OldCurrency = Balances;
    type Validators = Historical;
	type ValidatorId = sp_runtime::traits::ConvertInto;
    type RuntimeHoldReason = RuntimeHoldReason;
    type Currency = Balances;
    type MaxExposurePageSize = ConstU32<256>;
    type MaxValidatorSet = ConstU32<1000>;
    type Filter = Nothing;
    type MaxControllersInDeprecationBatch = MaxControllersInDeprecationBatch;
    type UnixTime = Timestamp;
    type CurrencyToVote = U128CurrencyToVote;
    type RewardRemainder = (); // burn
    type RuntimeEvent = RuntimeEvent;
    type Slash = (); // burn slashed rewards
    type Reward = (); // rewards are minted from the void
    type SessionsPerEra = SessionsPerEra;
    type BondingDuration = BondingDuration;
    type SlashDeferDuration = SlashDeferDuration;
    type SessionInterface = Self;
    type NextNewSession = Session;
    type WeightInfo = ();
    type ElectionProvider = ElectionProviderMultiPhase;
    type EraPayout = pallet_staking::ConvertCurve<RewardCurve>;
    type GenesisElectionProvider = onchain::OnChainExecution<OnChainSeqPhragmen>;
    type TargetList = pallet_staking::UseValidatorsMap<Self>;
    type MaxUnlockingChunks = ConstU32<32>;
    type HistoryDepth = HistoryDepth;
    type BenchmarkingConfig = StakingBenchmarkingConfig;
    type AdminOrigin = EitherOfDiverse<
        EnsureRoot<AccountId>,
        pallet_collective::EnsureProportionAtLeast<AccountId, TechCouncilInstance, 3, 4>,
    >;
    type CurrencyBalance = Balance;
    type VoterList = VoterList;
    type NominationsQuota = pallet_staking::FixedNominationsQuota<MAX_QUOTA_NOMINATIONS>;
    type EventListeners = NominationPools;
}
```

**Comment by arunjot12** [comment]
I tried setting the epoch to 6 minutes, but the issue still persists. I observed that when I start the chain with a 1-minute epoch and a 1-minute era, it falls back to the instant fallback. On the other hand, when I use a 2-minute epoch and a 4-minute era, the elections proceed with unsigned solutions. However, the problem remains the same in both cases: if I stop the node and restart it after skipping an era, it shows SnapshotUnavailable.

**Comment by sigurpol** [comment]
A-ah, you are not dealing with multi-block pallet but with the multi-phase one,  I missed that from your previous messages!

```rust
    type ElectionProvider = ElectionProviderMultiPhase;
```

**Comment by arunjot12** [comment]
Still why? The substrate node uses the same [https://github.com/paritytech/polkadot-sdk/blob/master/substrate/bin/node/runtime/src/lib.rs#L755](url)

**Comment by sigurpol** [comment]
I would let @kianenigma  comment on EPM Snapshot Persistence issues. 
If you want to use multi-block and not multi-phase, then a better reference for the multi-block use case is actually the westend asset-hub runtime. 
Note that in the scope of AHM, we have migrated Westend and Paseo to the new multi-block / staking-async approach and soon Kusama and Polkadot will be migrated too. I am not sure about the future of the EPM and the legacy staking pallets at all after AHM is migrated (Kian again, pls comment 🙏 )

**Comment by arunjot12** [comment]
Actually I've upgraded my chain from release-polkadot-1.1.0 to branch stable2506. Why this issue is occuring on my chain?. It is working on substrate stable2506.  It would really help me if you know what parameter i've missed on upgrading.

**Comment by sigurpol** [comment]
Keep in mind that  the issue #8302  and the related  fix  were about  being stuck in Emergency phase in the staking-async/multi-block setup, which is not what you are dealing with in your setup. My apologies for the misunderstanding around your use-case (staking  + multi-phase). Probably #9605 is a better place where to continue the discussion then. I have pinged @kianenigma  and hopefully he can provide you assistance soon.
